name: record
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0-48.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  pretty_dio_logger: ^1.1.1
  cached_network_image: ^3.1.0+1
  modal_bottom_sheet: ^2.0.0
  time_range_picker: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  photo_view: ^0.13.0
  flutter_image_compress: ^1.1.0
  flutter_svg: ^1.0.0
  tapioca: ^1.0.5+2
  gallery_saver: ^2.3.2
  video_player: ^2.2.18
#  //camera: ^0.9.4+11

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: InterBold
      fonts:
        - asset: assets/fonts/inter_bold.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/inter_medium.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/inter_regular.ttf